### ISSUE TITLE
how to training on new custom dataset?

### ISSUE THREAD

**Issue by sticky-ai** [liznerski/eoe#1]
Hello! Thank you for sharing code.
The FCDD you created before is working fine for me.

I'm trying to train EOE on my own dataset.
But it's a hard to do. how can i do?

**Comment by pantment** [comment]
Hello! I am trying to train EOE on my own dataset too. Did you do it ?

**Comment by liznerski** [comment]
Hey. 

I implemented this feature with commit e4dbb81. 
I also added some lines on this to the readme.

Hope it helps! :)
